# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10b6018e3c3c1cdecf33aa00eea2a1df0e646443be1bc0ccd228e7ac3c79988983b54e4b89aebb501fd7e869b50e588f4c66637cf2037f56360f8f1dba775ce3

test:
  secret_key_base: 98032147a824e1185275cb7560f0d6297a616f5e14fb783f0b3b5726582f7e188ca14dd719d2573723a756e5d7b48d0523ed19906c6ba80ea1167fa77c4490c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
