// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_cognito_identity_pool_id : 'us-east-1:9c48b177-cc33-4f19-ae37-cd5da09ca2bb',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'subleasy-hosting-mobilehub-748217910',
aws_content_delivery_bucket_region : 'us-east-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd1jz166euvd9w0.cloudfront.net',
aws_project_id : 'bd29d736-7a44-4a93-ac08-1ad582082d5d',
aws_project_name : 'subleasy',
aws_project_region : 'us-east-1',
aws_resource_name_prefix : 'subleasy-mobilehub-748217910',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});